spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: test

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hiberies:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace
